name: mecrosspro-system

on:
  push:
    branches: [develop]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Make zip file
        run: |
          zip -r dist.zip ./*

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: 'mecrosspro-system'
          environment_name: 'Mecrossprosystem-env-dev'
          region: ap-northeast-2
          version_label: 'mecrosspro-system-${{ github.run_number }}'
          deployment_package: dist.zip
