name: mecrosspro-system-staging

on:
  push:
    branches: [staging]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Make zip file
        run: |
          zip -r dist.zip ./dist/* ./package.json ./.platform/* ./.ebextensions/*
      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: 'mecrosspro-system'
          environment_name: 'staging'
          region: ap-northeast-2
          version_label: 'mecrosspro-system-staging-${{ github.run_number }}'
          deployment_package: dist.zip
